# Generated by Django 3.1.5 on 2021-01-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_temprecipe_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprecipe',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
