# Generated by Django 3.1.5 on 2021-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_temprecipe_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprecipe',
            name='snippet',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
